//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advance_Mast
    {
        public int VNO { get; set; }
        public int ENO { get; set; }
        public string Comp_Code { get; set; }
        public Nullable<decimal> AMT { get; set; }
        public Nullable<decimal> BalAmt { get; set; }
        public Nullable<int> INST { get; set; }
        public Nullable<int> InstBal { get; set; }
        public Nullable<System.DateTime> ADVON { get; set; }
        public Nullable<int> acct_Vno { get; set; }
        public Nullable<System.DateTime> Acct_Vdate { get; set; }
        public string ChqNo { get; set; }
        public Nullable<System.DateTime> ChqDate { get; set; }
        public string Bank_Name { get; set; }
        public Nullable<System.DateTime> WEFrom { get; set; }
        public Nullable<System.DateTime> EffectedFrom { get; set; }
    }
}
