//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADVance_Trans
    {
        public int VNo { get; set; }
        public int Eno { get; set; }
        public string Comp_Code { get; set; }
        public int InstNo { get; set; }
        public Nullable<decimal> AdvTotAmt { get; set; }
        public Nullable<decimal> AdvDedAmt { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
    }
}
