//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTENDANCE
    {
        public int ENO { get; set; }
        public System.DateTime WDATE { get; set; }
        public int SNO { get; set; }
        public string Comp_Code { get; set; }
        public string STATUS { get; set; }
        public string LType { get; set; }
        public Nullable<System.DateTime> Time_Out_Date { get; set; }
        public Nullable<System.DateTime> TIME_IN { get; set; }
        public Nullable<System.DateTime> TIME_OUT { get; set; }
        public string PER { get; set; }
        public string LNodeduct { get; set; }
        public string ENodeduct { get; set; }
        public string LPer { get; set; }
        public string EPer { get; set; }
        public string AUTH { get; set; }
        public string shift { get; set; }
        public string Time_Worked { get; set; }
        public string Time_tobeCal { get; set; }
        public string Remarks { get; set; }
        public string TrType { get; set; }
        public string UserId { get; set; }
        public Nullable<int> LNo { get; set; }
        public string Freeze { get; set; }
        public Nullable<int> late { get; set; }
        public Nullable<int> lc { get; set; }
        public Nullable<int> eo { get; set; }
        public Nullable<int> ot { get; set; }
    }
}
