//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendSummary
    {
        public int EmpNo { get; set; }
        public int CurMonth { get; set; }
        public int CurYear { get; set; }
        public string CL { get; set; }
        public string EL { get; set; }
        public string COFF { get; set; }
        public string LOP { get; set; }
        public Nullable<int> Holidays { get; set; }
        public Nullable<int> PresentDays { get; set; }
        public Nullable<int> Total { get; set; }
        public string UserId { get; set; }
    }
}
