//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiAnnualReport
    {
        public string FormType { get; set; }
        public int BiAnnualYear { get; set; }
        public int BiAnnualMonth { get; set; }
        public int SNo { get; set; }
        public string Designation { get; set; }
        public string PrintAs { get; set; }
        public string Women { get; set; }
        public string Men { get; set; }
        public Nullable<int> Total { get; set; }
        public string Comments { get; set; }
        public string UserId { get; set; }
    }
}
