//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coffs_Trans
    {
        public int Eno { get; set; }
        public string Comp_code { get; set; }
        public string Shift { get; set; }
        public System.DateTime Wdate { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
        public Nullable<System.DateTime> Time_in { get; set; }
        public Nullable<System.DateTime> Time_out { get; set; }
        public Nullable<System.DateTime> Total_Wtime { get; set; }
        public Nullable<decimal> No_of_Coffs { get; set; }
        public string Authority { get; set; }
        public string Remarks { get; set; }
    }
}
