//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoffTemp
    {
        public int SlNo { get; set; }
        public Nullable<int> SNo { get; set; }
        public Nullable<int> Eno { get; set; }
        public string ExtraTime { get; set; }
        public Nullable<System.DateTime> TimeIn_Date { get; set; }
        public Nullable<System.DateTime> TimeOut_Date { get; set; }
        public string Time_In { get; set; }
        public string Time_Out { get; set; }
        public string DayName { get; set; }
        public Nullable<System.DateTime> STime { get; set; }
        public string NoOfDays { get; set; }
    }
}
