//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COFFREQMAY
    {
        public int ReqNo { get; set; }
        public string Comp_Code { get; set; }
        public Nullable<System.DateTime> ReqDate { get; set; }
        public Nullable<int> Eno { get; set; }
        public string Shift { get; set; }
        public Nullable<System.DateTime> WDate { get; set; }
        public string Stime { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public string CTime { get; set; }
        public string TotHrs { get; set; }
        public Nullable<decimal> No_of_Coffs { get; set; }
        public string Purpose { get; set; }
        public string Authority { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string StatusRem { get; set; }
        public string UserId { get; set; }
        public string SysName { get; set; }
        public string DayName { get; set; }
    }
}
