//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Id { get; set; }
        public string CompId { get; set; }
        public string Comp_Name { get; set; }
        public string Comp_Descp { get; set; }
        public string Comp_Addr { get; set; }
        public string Reports_Path { get; set; }
        public string DSN { get; set; }
        public string Server_Name { get; set; }
        public string Setup_Pass { get; set; }
        public string YearName { get; set; }
        public Nullable<System.DateTime> YearSDate { get; set; }
        public Nullable<System.DateTime> YearCDate { get; set; }
        public string DbName { get; set; }
        public string BackupDevice { get; set; }
        public Nullable<System.DateTime> Estd_Year { get; set; }
    }
}
