//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyAttend
    {
        public string Wdate { get; set; }
        public int Eno { get; set; }
        public string Ename { get; set; }
        public string TrType { get; set; }
        public string TimeIn { get; set; }
        public string TimeOut_Date { get; set; }
        public string TimeOut { get; set; }
        public string Shit { get; set; }
        public string Lper { get; set; }
        public string LperNDed { get; set; }
        public string EPer { get; set; }
        public string EPerNDed { get; set; }
        public string User_ID { get; set; }
        public string Status { get; set; }
        public string worked { get; set; }
    }
}
