//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaysCount
    {
        public int SlNo { get; set; }
        public Nullable<int> SWDays { get; set; }
        public Nullable<int> NoOfMDaysWkd { get; set; }
        public Nullable<int> NoOfMDaysAbsnt { get; set; }
    }
}
