//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpAttandance
    {
        public int EmpNo { get; set; }
        public string Ename { get; set; }
        public string Designation { get; set; }
        public string Wdate { get; set; }
        public string TimeIn { get; set; }
        public string TOutDate { get; set; }
        public string TimeOut { get; set; }
        public string TotHrs { get; set; }
        public string shift { get; set; }
        public string LType { get; set; }
        public string Per { get; set; }
        public string Auth { get; set; }
        public string Status { get; set; }
    }
}
