//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empyrsalreport
    {
        public string comp_code { get; set; }
        public int eno { get; set; }
        public System.DateTime pmon { get; set; }
        public string ename { get; set; }
        public Nullable<decimal> GrossSal { get; set; }
        public Nullable<decimal> basic { get; set; }
        public Nullable<decimal> da { get; set; }
        public Nullable<decimal> Other_Allow { get; set; }
        public Nullable<decimal> hra { get; set; }
        public Nullable<decimal> Conv { get; set; }
        public Nullable<decimal> advance_ded { get; set; }
        public Nullable<decimal> Pf_Ded { get; set; }
        public Nullable<decimal> Esi_Ded { get; set; }
        public Nullable<decimal> ptax_ded { get; set; }
        public Nullable<decimal> Tds_ded { get; set; }
        public Nullable<decimal> late_ded { get; set; }
        public Nullable<decimal> Lic_amt { get; set; }
        public Nullable<decimal> Actual_Netsal { get; set; }
        public Nullable<decimal> other_ded { get; set; }
        public Nullable<decimal> tot_ded { get; set; }
    }
}
