//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESIContribution
    {
        public int SNo { get; set; }
        public int Eno { get; set; }
        public string Ename { get; set; }
        public string ESINo { get; set; }
        public Nullable<int> Present_Days { get; set; }
        public Nullable<decimal> GrossSalary { get; set; }
        public Nullable<decimal> EmployeeShare { get; set; }
        public Nullable<decimal> EmployerShare { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int ESIMonth { get; set; }
        public int ESIYear { get; set; }
        public string UserId { get; set; }
        public string CompCode { get; set; }
    }
}
