//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EsiHalfYrTemp
    {
        public int ENO { get; set; }
        public string ENAME { get; set; }
        public System.DateTime PMON { get; set; }
        public Nullable<decimal> GrossSal { get; set; }
        public string ESINO { get; set; }
        public Nullable<int> Present_Days { get; set; }
        public string Comp_code { get; set; }
    }
}
