//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcessEL
    {
        public int ENO { get; set; }
        public string EName { get; set; }
        public Nullable<int> TotELs { get; set; }
        public Nullable<int> ExsELs { get; set; }
    }
}
