//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMR1
    {
        public string ENAME { get; set; }
        public Nullable<int> NO { get; set; }
        public Nullable<int> PFMon { get; set; }
        public Nullable<decimal> Wages { get; set; }
        public Nullable<int> DOJ { get; set; }
        public Nullable<int> DOL { get; set; }
        public Nullable<decimal> EPF { get; set; }
        public Nullable<decimal> EPFDiff { get; set; }
        public Nullable<decimal> PensionFund { get; set; }
        public string RFL { get; set; }
        public Nullable<int> NCP { get; set; }
    }
}
