//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormAR
    {
        public int Sno { get; set; }
        public Nullable<int> Year { get; set; }
        public string RegNo { get; set; }
        public string CompName { get; set; }
        public string CompAddr { get; set; }
        public string OccName { get; set; }
        public string OccAddr { get; set; }
        public string MgrName { get; set; }
        public string MgrAddr { get; set; }
        public string ESICode { get; set; }
        public string SSICode { get; set; }
        public string Nature { get; set; }
        public Nullable<int> WorkDays { get; set; }
        public Nullable<int> MManDays { get; set; }
        public Nullable<int> WMandays { get; set; }
        public Nullable<int> CManDays { get; set; }
        public Nullable<decimal> AvgMEmployed { get; set; }
        public Nullable<decimal> AvgWEmployed { get; set; }
        public Nullable<decimal> AvgCEmployed { get; set; }
        public string OTMHrs { get; set; }
        public string OTWHrs { get; set; }
        public string OTCHrs { get; set; }
        public Nullable<decimal> OTMAmt { get; set; }
        public Nullable<decimal> OTWAmt { get; set; }
        public Nullable<decimal> OTCAmt { get; set; }
        public Nullable<decimal> AvgNoWorkers { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> BonusAmt { get; set; }
        public Nullable<int> BonusRate { get; set; }
        public Nullable<decimal> WelfareAmt { get; set; }
        public string CDWater { get; set; }
        public string Canteen { get; set; }
        public string SafetyOfficers { get; set; }
        public string Shelters { get; set; }
        public string AmbulanceRoom { get; set; }
        public string Creche { get; set; }
        public string MedicalOfficer { get; set; }
        public string WelfareOfficer { get; set; }
        public Nullable<int> FatalAcc { get; set; }
        public Nullable<int> NonFatalAcc { get; set; }
        public Nullable<int> DaysLost { get; set; }
        public Nullable<int> MaternityCases { get; set; }
        public Nullable<int> MedicalCases { get; set; }
        public Nullable<int> MisCarriageCases { get; set; }
        public Nullable<int> Illnessleave { get; set; }
        public Nullable<int> MaternityAmt { get; set; }
        public Nullable<int> EntitledWorkers { get; set; }
        public Nullable<int> AllowedWorkers { get; set; }
        public Nullable<decimal> AnnualAmt { get; set; }
    }
}
