//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form2
    {
        public int Eno { get; set; }
        public string Ename { get; set; }
        public string NomName { get; set; }
        public string NomRelation { get; set; }
        public string NomDob { get; set; }
        public string NomAdd { get; set; }
        public string GuardianName { get; set; }
        public string GuardAdd { get; set; }
        public string NomFName { get; set; }
        public string LocalOffice { get; set; }
        public string Dispensary { get; set; }
        public Nullable<decimal> PfShare { get; set; }
    }
}
