//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form5
    {
        public int SlNo { get; set; }
        public Nullable<int> PfNo { get; set; }
        public string EmpName { get; set; }
        public string Fname { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Sex { get; set; }
        public string DoF { get; set; }
        public string FundService { get; set; }
    }
}
