//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormF
    {
        public int Sno { get; set; }
        public Nullable<int> Year { get; set; }
        public string EmployerName { get; set; }
        public string Designation { get; set; }
        public string WelfareAddress { get; set; }
        public string CompName { get; set; }
        public string CompAddr { get; set; }
        public string Class { get; set; }
        public string Others { get; set; }
        public Nullable<int> NoofEmp { get; set; }
        public Nullable<int> NoofEmpContr { get; set; }
        public Nullable<decimal> EmployeeAmt { get; set; }
        public Nullable<decimal> EmployerAmt { get; set; }
        public string FullPayment { get; set; }
        public Nullable<decimal> AmtPaid { get; set; }
        public string Reasons { get; set; }
        public string PaymentMode { get; set; }
        public string DDNo { get; set; }
        public Nullable<System.DateTime> DDDate { get; set; }
        public string BankName { get; set; }
        public string Branch { get; set; }
        public string Address { get; set; }
        public string Remarks { get; set; }
    }
}
