//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grat_Payments
    {
        public int ENo { get; set; }
        public int PaySno { get; set; }
        public string CCode { get; set; }
        public string Bank_name { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public Nullable<System.DateTime> PaidOn { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public Nullable<decimal> TotalAmt { get; set; }
        public Nullable<decimal> PaidTillNow { get; set; }
        public string Remarks { get; set; }
    }
}
