//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Increment
    {
        public int Eno { get; set; }
        public int Sno { get; set; }
        public string Comp_code { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<decimal> Start_Sal { get; set; }
        public Nullable<System.DateTime> Incr_Date { get; set; }
        public Nullable<decimal> Incr_Sal { get; set; }
        public Nullable<System.DateTime> last_incr_date { get; set; }
        public string Remarks { get; set; }
        public string EffFrom { get; set; }
        public string Grade { get; set; }
    }
}
