//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEV_MAST
    {
        public int ENO { get; set; }
        public string Comp_Code { get; set; }
        public Nullable<decimal> Cl_Open { get; set; }
        public Nullable<int> EL_Open { get; set; }
        public Nullable<decimal> Coff_Open { get; set; }
        public Nullable<decimal> CL { get; set; }
        public Nullable<int> EL { get; set; }
        public Nullable<int> SL { get; set; }
        public Nullable<int> ML { get; set; }
        public Nullable<decimal> COFF { get; set; }
        public Nullable<decimal> CLBAL { get; set; }
        public Nullable<int> ELBAL { get; set; }
        public Nullable<int> SLBAL { get; set; }
        public Nullable<int> MLBAL { get; set; }
        public Nullable<decimal> COFFBAL { get; set; }
    }
}
