//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEV_TRANS
    {
        public int LNo { get; set; }
        public int ENO { get; set; }
        public string Comp_Code { get; set; }
        public string LTYPE { get; set; }
        public System.DateTime LDATE { get; set; }
        public Nullable<System.DateTime> FDATE { get; set; }
        public Nullable<System.DateTime> TDATE { get; set; }
        public Nullable<decimal> No_Of_Days { get; set; }
        public string Reason { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> RDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public Nullable<System.DateTime> Leave_Adate { get; set; }
        public string Auth { get; set; }
        public Nullable<int> sno { get; set; }
        public Nullable<decimal> clbal { get; set; }
        public Nullable<int> elbal { get; set; }
        public Nullable<decimal> coffbal { get; set; }
        public string pldetails { get; set; }
        public Nullable<decimal> ClBalAfter { get; set; }
        public Nullable<int> ElBalAfter { get; set; }
        public Nullable<decimal> CoffBalAfter { get; set; }
        public string Freeze { get; set; }
    }
}
