//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicStatu
    {
        public int eno { get; set; }
        public string ename { get; set; }
        public string lic_sts { get; set; }
        public decimal lic_NO { get; set; }
        public Nullable<decimal> LicAmt { get; set; }
    }
}
