//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYREG
    {
        public int ENO { get; set; }
        public System.DateTime PMON { get; set; }
        public string Comp_Code { get; set; }
        public Nullable<decimal> act_basic { get; set; }
        public Nullable<decimal> act_da { get; set; }
        public Nullable<decimal> act_hra { get; set; }
        public Nullable<decimal> act_conv { get; set; }
        public Nullable<decimal> act_oallow { get; set; }
        public Nullable<decimal> act_ChdEduAll { get; set; }
        public Nullable<System.DateTime> Fdate { get; set; }
        public Nullable<System.DateTime> Tdate { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> BASIC { get; set; }
        public Nullable<decimal> DA { get; set; }
        public Nullable<decimal> Other_allow { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> CONV { get; set; }
        public Nullable<decimal> ChdEduAll { get; set; }
        public Nullable<decimal> Advance_Ded { get; set; }
        public Nullable<decimal> IT_ded { get; set; }
        public Nullable<decimal> PF_Ded { get; set; }
        public Nullable<decimal> ESI_Ded { get; set; }
        public Nullable<decimal> PTax_Ded { get; set; }
        public Nullable<decimal> TDS_Ded { get; set; }
        public Nullable<decimal> Late_Ded { get; set; }
        public Nullable<decimal> Lic_Amt { get; set; }
        public Nullable<decimal> OT_Amt { get; set; }
        public Nullable<decimal> GrossSal { get; set; }
        public Nullable<decimal> NetSal { get; set; }
        public Nullable<decimal> Actual_NetSal { get; set; }
        public Nullable<int> Absent_Days { get; set; }
        public Nullable<int> Present_Days { get; set; }
        public Nullable<int> Available_Days { get; set; }
        public Nullable<decimal> Tot_Ded { get; set; }
        public Nullable<decimal> Other_Earnings { get; set; }
        public Nullable<decimal> Other_Ded { get; set; }
        public string Other_Remarks { get; set; }
        public Nullable<decimal> CL_Bal { get; set; }
        public Nullable<decimal> EL_Bal { get; set; }
        public Nullable<decimal> PrevMon_Ded { get; set; }
        public string Freeze { get; set; }
        public Nullable<decimal> prod_bonus { get; set; }
        public Nullable<decimal> tiffin_bill { get; set; }
        public Nullable<decimal> currency_rate { get; set; }
        public Nullable<decimal> net_pay_Tk { get; set; }
        public Nullable<decimal> FH { get; set; }
        public Nullable<decimal> SH { get; set; }
        public Nullable<decimal> ML { get; set; }
        public Nullable<decimal> SL { get; set; }
        public Nullable<decimal> ot_rate { get; set; }
        public Nullable<decimal> ot_hr { get; set; }
        public Nullable<decimal> samplepay { get; set; }
        public Nullable<decimal> finededuct { get; set; }
        public Nullable<decimal> prodwages { get; set; }
        public Nullable<decimal> otherpay { get; set; }
        public Nullable<decimal> firststsamity { get; set; }
        public Nullable<decimal> secondsamity { get; set; }
        public Nullable<decimal> milk { get; set; }
        public Nullable<decimal> advancepay { get; set; }
        public Nullable<int> sampleday { get; set; }
        public Nullable<decimal> noworkpay { get; set; }
    }
}
