//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISSION1
    {
        public int ID { get; set; }
        public string UNAME { get; set; }
        public string menu_name { get; set; }
        public string menuCtrl_Name { get; set; }
        public string Permitted { get; set; }
        public string Operation { get; set; }
    }
}
