//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFContribution
    {
        public int SNo { get; set; }
        public Nullable<int> ENo { get; set; }
        public Nullable<int> AccountNo { get; set; }
        public string EName { get; set; }
        public string MonSalary { get; set; }
        public string MonDa { get; set; }
        public Nullable<decimal> PFSalary { get; set; }
        public Nullable<decimal> EPF { get; set; }
        public Nullable<decimal> EPF1 { get; set; }
        public Nullable<decimal> FPF { get; set; }
        public Nullable<decimal> EDLI { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int PFMonth { get; set; }
        public int PFYear { get; set; }
        public string UserID { get; set; }
        public string CompCode { get; set; }
    }
}
