//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFSummary
    {
        public int HeadId { get; set; }
        public string Head { get; set; }
        public string AccountNo { get; set; }
        public Nullable<decimal> PFSalary { get; set; }
        public string EmployeePer { get; set; }
        public string EmployerPer { get; set; }
        public string EmployeeShare { get; set; }
        public Nullable<decimal> EmployerShare { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int PFMonth { get; set; }
        public int PFYear { get; set; }
        public string UserId { get; set; }
        public string CompCode { get; set; }
    }
}
