//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvidentFund
    {
        public int PFMonth { get; set; }
        public int PFYear { get; set; }
        public string UserId { get; set; }
        public string CompCode { get; set; }
        public Nullable<int> Subscribers { get; set; }
        public Nullable<decimal> WagesDue { get; set; }
        public Nullable<decimal> Ac1_EmployerShare { get; set; }
        public Nullable<decimal> Ac2_EmployerShare { get; set; }
        public Nullable<decimal> Ac10_EmployerShare { get; set; }
        public Nullable<decimal> Ac21_EmployerShare { get; set; }
        public Nullable<decimal> Ac22_EmployerShare { get; set; }
        public Nullable<decimal> Ac1_EmployeeShare { get; set; }
        public Nullable<decimal> Ac2_EmployeeShare { get; set; }
        public Nullable<decimal> Ac10_EmployeeShare { get; set; }
        public Nullable<decimal> Ac21_EmployeeShare { get; set; }
        public Nullable<decimal> Ac22_EmployeeShare { get; set; }
        public Nullable<decimal> Ac1_AdmnCharges { get; set; }
        public Nullable<decimal> Ac2_AdmnCharges { get; set; }
        public Nullable<decimal> Ac10_AdmnCharges { get; set; }
        public Nullable<decimal> Ac21_AdmnCharges { get; set; }
        public Nullable<decimal> Ac22_AdmnCharges { get; set; }
        public Nullable<decimal> Ac1_InspCharges { get; set; }
        public Nullable<decimal> Ac2_InspCharges { get; set; }
        public Nullable<decimal> Ac10_InspCharges { get; set; }
        public Nullable<decimal> Ac21_InspCharges { get; set; }
        public Nullable<decimal> Ac22_InspCharges { get; set; }
        public Nullable<decimal> Ac1_PenalDamages14 { get; set; }
        public Nullable<decimal> Ac2_PenalDamages14 { get; set; }
        public Nullable<decimal> Ac10_PenalDamages14 { get; set; }
        public Nullable<decimal> Ac21_PenalDamages14 { get; set; }
        public Nullable<decimal> Ac22_PenalDamages14 { get; set; }
        public Nullable<decimal> Ac1_PenalDamages7 { get; set; }
        public Nullable<decimal> Ac2_PenalDamages7 { get; set; }
        public Nullable<decimal> Ac10_PenalDamages7 { get; set; }
        public Nullable<decimal> Ac21_PenalDamages7 { get; set; }
        public Nullable<decimal> Ac22_PenalDamages7 { get; set; }
        public Nullable<decimal> Ac1_MiscPayment { get; set; }
        public Nullable<decimal> Ac2_MiscPayment { get; set; }
        public Nullable<decimal> Ac10_MiscPayment { get; set; }
        public Nullable<decimal> Ac21_MiscPayment { get; set; }
        public Nullable<decimal> Ac22_MiscPayment { get; set; }
        public string ModeOfPayment { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string BankName { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string DepositorName { get; set; }
        public string DepBankCode { get; set; }
        public string DepBankName { get; set; }
    }
}
