//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTaxReturn
    {
        public int SNo { get; set; }
        public int PTaxMonth { get; set; }
        public int PTaxYear { get; set; }
        public string SalRange { get; set; }
        public string NoOfEmp { get; set; }
        public string PTax_Ded { get; set; }
        public string TotalTax { get; set; }
        public Nullable<decimal> Amount_Paid { get; set; }
        public string UserId { get; set; }
        public string Comp_Code { get; set; }
    }
}
