//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuarterReport
    {
        public string FormType { get; set; }
        public int QuarterYear { get; set; }
        public int QuarterMonth { get; set; }
        public Nullable<int> PQuarterMen { get; set; }
        public Nullable<int> PQuarterWomen { get; set; }
        public Nullable<int> CQuarterMen { get; set; }
        public Nullable<int> CQuarterWomen { get; set; }
        public string Reason1b { get; set; }
        public string NOOccurred { get; set; }
        public string LEE { get; set; }
        public string CEE { get; set; }
        public string Filled { get; set; }
        public string Source { get; set; }
        public string Reason2b { get; set; }
        public string Manpower { get; set; }
        public string UserId { get; set; }
    }
}
