//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RANx
    {
        public string Col_Name { get; set; }
        public decimal Range_From { get; set; }
        public decimal Range_To { get; set; }
        public decimal Range_amt { get; set; }
    }
}
