//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepAttend
    {
        public int id { get; set; }
        public int eno { get; set; }
        public Nullable<System.DateTime> wdate { get; set; }
        public string time_In { get; set; }
        public Nullable<System.DateTime> TimeOut_Date { get; set; }
        public string Time_Out { get; set; }
        public string TotHrs { get; set; }
        public string Shift { get; set; }
        public string Per { get; set; }
        public string Auth { get; set; }
        public string Sts { get; set; }
        public string LType { get; set; }
    }
}
