//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepAttendance
    {
        public int Eno { get; set; }
        public string User_id { get; set; }
        public string Day1TIn { get; set; }
        public string Day1TOut { get; set; }
        public string Day2TIn { get; set; }
        public string Day2TOut { get; set; }
        public string Day3TIn { get; set; }
        public string Day3TOut { get; set; }
        public string Day4TIn { get; set; }
        public string Day4TOut { get; set; }
        public string Day5TIn { get; set; }
        public string Day5TOut { get; set; }
        public string Day6TIn { get; set; }
        public string Day6TOut { get; set; }
        public string Day7TIn { get; set; }
        public string Day7TOut { get; set; }
        public string Day8TIn { get; set; }
        public string Day8TOut { get; set; }
        public string Day9TIn { get; set; }
        public string Day9TOut { get; set; }
        public string Day10TIn { get; set; }
        public string Day10TOut { get; set; }
        public string Day11TIn { get; set; }
        public string Day11TOut { get; set; }
        public string Day12TIn { get; set; }
        public string Day12TOut { get; set; }
        public string Day13TIn { get; set; }
        public string Day13TOut { get; set; }
        public string Day14TIn { get; set; }
        public string Day14TOut { get; set; }
        public string Day15TIn { get; set; }
        public string Day15TOut { get; set; }
        public string Day16TIn { get; set; }
        public string Day16TOut { get; set; }
        public string Day17TIn { get; set; }
        public string Day17TOut { get; set; }
        public string Day18TIn { get; set; }
        public string Day18TOut { get; set; }
        public string Day19TIn { get; set; }
        public string Day19TOut { get; set; }
        public string Day20TIn { get; set; }
        public string Day20TOut { get; set; }
        public string Day21TIn { get; set; }
        public string Day21TOut { get; set; }
        public string Day22TIn { get; set; }
        public string Day22TOut { get; set; }
        public string Day23TIn { get; set; }
        public string Day23TOut { get; set; }
        public string Day24TIn { get; set; }
        public string Day24TOut { get; set; }
        public string Day25TIn { get; set; }
        public string Day25TOut { get; set; }
        public string Day26TIn { get; set; }
        public string Day26TOut { get; set; }
        public string Day27TIn { get; set; }
        public string Day27TOut { get; set; }
        public string Day28TIn { get; set; }
        public string Day28TOut { get; set; }
        public string Day29TIn { get; set; }
        public string Day29TOut { get; set; }
        public string Day30TIn { get; set; }
        public string Day30TOut { get; set; }
        public string Day31TIn { get; set; }
        public string Day31TOut { get; set; }
        public string Comp_code { get; set; }
    }
}
