//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepCoff
    {
        public int Id { get; set; }
        public int Eno { get; set; }
        public string Ename { get; set; }
        public Nullable<System.DateTime> WDate { get; set; }
        public string DayName { get; set; }
        public string Time_in { get; set; }
        public Nullable<System.DateTime> TOut_Date { get; set; }
        public string Time_Out { get; set; }
        public string TotalHrs { get; set; }
        public Nullable<decimal> Coffs { get; set; }
        public string Authority { get; set; }
        public string Remarks { get; set; }
    }
}
