//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPTOT
    {
        public int ENO { get; set; }
        public string ENAME { get; set; }
        public string OTIME { get; set; }
        public Nullable<decimal> GROSS { get; set; }
        public Nullable<int> NP { get; set; }
        public Nullable<decimal> PAY { get; set; }
        public Nullable<decimal> LUNCH { get; set; }
        public Nullable<decimal> TOTPAY { get; set; }
        public Nullable<decimal> SUNPAY { get; set; }
    }
}
