//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RULE
    {
        public Nullable<int> YEARCL { get; set; }
        public Nullable<int> MONTHCL { get; set; }
        public string APD { get; set; }
        public string ALLOWCL { get; set; }
        public Nullable<int> MINEL { get; set; }
        public Nullable<int> DAYEL { get; set; }
        public Nullable<int> CONTEL { get; set; }
        public Nullable<int> MAXEL { get; set; }
        public string ALLOWEL { get; set; }
        public Nullable<int> YEARSL { get; set; }
        public Nullable<int> NOSL { get; set; }
        public string ALLOWSL { get; set; }
        public Nullable<int> YEARML { get; set; }
        public Nullable<int> NOML { get; set; }
        public string ALLOWML { get; set; }
        public Nullable<System.DateTime> HDCS { get; set; }
        public Nullable<System.DateTime> HDCE { get; set; }
        public Nullable<int> NOHD { get; set; }
        public string ALLOWHDC { get; set; }
        public Nullable<System.DateTime> FDCS { get; set; }
        public Nullable<System.DateTime> FDCE { get; set; }
        public Nullable<int> NOFD { get; set; }
        public string ALLOWFDC { get; set; }
        public Nullable<System.DateTime> GPUT { get; set; }
        public Nullable<int> NOGD { get; set; }
        public string ALLOWGT { get; set; }
        public string OSTAY { get; set; }
        public string ALLOWOS { get; set; }
        public string ALLOWCF { get; set; }
        public System.DateTime ITIME { get; set; }
        public System.DateTime OTIME { get; set; }
        public decimal PFP { get; set; }
        public decimal ESIP { get; set; }
        public Nullable<System.DateTime> LTS { get; set; }
        public Nullable<System.DateTime> LTE { get; set; }
        public string HDCL { get; set; }
        public string EGO { get; set; }
        public string COVER { get; set; }
        public Nullable<int> CONV { get; set; }
        public string HDPD { get; set; }
    }
}
