//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rupayan
    {
        public int ID1 { get; set; }
        public string Name { get; set; }
        public Nullable<short> ID { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> Joining { get; set; }
        public string Department { get; set; }
        public Nullable<short> Grade { get; set; }
        public Nullable<double> Basic { get; set; }
        public Nullable<double> HouseRent { get; set; }
        public Nullable<double> Medical { get; set; }
        public Nullable<double> Gross { get; set; }
    }
}
