//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIFT_MASTER
    {
        public string SHIFT_NAME { get; set; }
        public string SHIFT_DESC { get; set; }
        public System.DateTime SHIFT_IN { get; set; }
        public System.DateTime SHIFT_OUT { get; set; }
        public Nullable<System.DateTime> LUNCH_START { get; set; }
        public Nullable<System.DateTime> LUNCH_END { get; set; }
        public bool NEXTDAY_FLAG { get; set; }
    }
}
