//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_style
    {
        public int styleID { get; set; }
        public string StyleName { get; set; }
        public string style_desc { get; set; }
        public string buyer { get; set; }
        public Nullable<decimal> order_qty { get; set; }
    }
}
