//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblextrapaycode
    {
        public int uid { get; set; }
        public int year { get; set; }
        public int month { get; set; }
        public int empid { get; set; }
        public string paycode { get; set; }
        public string payvalue { get; set; }
        public string payformula { get; set; }
        public string adjtype { get; set; }
    }
}
