//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStyleRate
    {
        public int uid { get; set; }
        public string OperationName { get; set; }
        public Nullable<int> fk_styleID { get; set; }
        public string Stylename { get; set; }
        public Nullable<int> fk_partsID { get; set; }
        public string partsCategory { get; set; }
        public string Partsname { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string remarks { get; set; }
    }
}
