//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temppayreg
    {
        public string comp_code { get; set; }
        public int eno { get; set; }
        public System.DateTime pmon { get; set; }
        public string ename { get; set; }
        public Nullable<decimal> grosssal { get; set; }
        public Nullable<decimal> basic { get; set; }
        public Nullable<decimal> da { get; set; }
        public Nullable<decimal> other_allow { get; set; }
        public Nullable<decimal> hra { get; set; }
        public Nullable<decimal> conv { get; set; }
        public Nullable<decimal> advance_ded { get; set; }
        public Nullable<decimal> pf_ded { get; set; }
        public Nullable<decimal> esi_ded { get; set; }
        public Nullable<decimal> ptax_ded { get; set; }
        public Nullable<decimal> tds_ded { get; set; }
        public Nullable<decimal> late_ded { get; set; }
        public Nullable<decimal> lic_amt { get; set; }
        public Nullable<decimal> actual_netsal { get; set; }
        public Nullable<decimal> other_ded { get; set; }
    }
}
