//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempyrsal
    {
        public string COMP_CODE { get; set; }
        public int ENO { get; set; }
        public System.DateTime PMON { get; set; }
        public string ENAME { get; set; }
        public Nullable<decimal> GROSSSAL { get; set; }
        public Nullable<decimal> BASIC { get; set; }
        public Nullable<decimal> DA { get; set; }
        public Nullable<decimal> OTHER_ALLOW { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> CONV { get; set; }
        public Nullable<decimal> ADVANCE_DED { get; set; }
        public Nullable<decimal> PF_DED { get; set; }
        public Nullable<decimal> ESI_DED { get; set; }
        public Nullable<decimal> PTAX_DED { get; set; }
        public Nullable<decimal> TDS_DED { get; set; }
        public Nullable<decimal> LATE_DED { get; set; }
        public Nullable<decimal> LIC_AMT { get; set; }
        public Nullable<decimal> ACTUAL_NETSAL { get; set; }
        public Nullable<decimal> OTHER_DED { get; set; }
    }
}
