//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_union_attn
    {
        public Nullable<int> ENO { get; set; }
        public Nullable<System.DateTime> WDATE { get; set; }
        public string STATUS { get; set; }
        public string shift { get; set; }
        public System.DateTime time_in { get; set; }
    }
}
