//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_production_report
    {
        public Nullable<int> eno { get; set; }
        public string ename { get; set; }
        public string OperationName { get; set; }
        public string Stylename { get; set; }
        public string PartsName { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string SSN { get; set; }
        public int eid { get; set; }
        public Nullable<int> Year { get; set; }
        public string Month { get; set; }
    }
}
