//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_day_sl
    {
        public Nullable<int> day_sl { get; set; }
        public System.DateTime TODAY { get; set; }
        public string Comp_Code { get; set; }
        public string WORH { get; set; }
        public string Shift { get; set; }
    }
}
