//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Deptwise_Emp
    {
        public string Dept { get; set; }
        public int ENO { get; set; }
        public string Comp_Code { get; set; }
        public string ENAME { get; set; }
        public string Qualification { get; set; }
        public string DESIGNATION { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public decimal BASIC { get; set; }
        public Nullable<decimal> DA { get; set; }
        public Nullable<decimal> OALL { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> CONV { get; set; }
        public string Bank_Ac { get; set; }
        public string AReg_Sno { get; set; }
        public string EMPSTATUS { get; set; }
        public string SSN { get; set; }
        public string shift { get; set; }
        public Nullable<int> SlNo { get; set; }
    }
}
