//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knith_Horizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_INCR
    {
        public int ENO { get; set; }
        public string ENAME { get; set; }
        public decimal BASIC { get; set; }
        public Nullable<decimal> DA { get; set; }
        public Nullable<decimal> OALL { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> CONV { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<System.DateTime> WEFROM { get; set; }
    }
}
